export const FLAGS = {
  'Mexico': '🇲🇽',
  'Czechia': '🇨🇿',
  'Korea Republic': '🇰🇷',
  'South Africa': '🇿🇦',
  'Canada': '🇨🇦',
  'Switzerland': '🇨🇭',
  'Qatar': '🇶🇦',
  'Bosnia and Herzegovina': '🇧🇦',
  'Brazil': '🇧🇷',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Haiti': '🇭🇹',
  'Morocco': '🇲🇦',
  'United States': '🇺🇸',
  'Türkiye': '🇹🇷',
  'Australia': '🇦🇺',
  'Paraguay': '🇵🇾',
  'Germany': '🇩🇪',
  'Ecuador': '🇪🇨',
  "Côte d'Ivoire": '🇨🇮',
  'Curaçao': '🇨🇼',
  'Netherlands': '🇳🇱',
  'Tunisia': '🇹🇳',
  'Sweden': '🇸🇪',
  'Japan': '🇯🇵',
  'Belgium': '🇧🇪',
  'New Zealand': '🇳🇿',
  'Iran': '🇮🇷',
  'Egypt': '🇪🇬',
  'Spain': '🇪🇸',
  'Uruguay': '🇺🇾',
  'Saudi Arabia': '🇸🇦',
  'Cabo Verde': '🇨🇻',
  'France': '🇫🇷',
  'Norway': '🇳🇴',
  'Iraq': '🇮🇶',
  'Senegal': '🇸🇳',
  'Argentina': '🇦🇷',
  'Jordan': '🇯🇴',
  'Austria': '🇦🇹',
  'Algeria': '🇩🇿',
  'Portugal': '🇵🇹',
  'Colombia': '🇨🇴',
  'Uzbekistan': '🇺🇿',
  'Congo DR': '🇨🇩',
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Panama': '🇵🇦',
  'Ghana': '🇬🇭',
  'Croatia': '🇭🇷',
}

export function flag(team) {
  return FLAGS[team] ?? '🏳️'
}

export const GROUP_COLORS = {
  A: '#22D3EE', B: '#F5C518', C: '#22C55E', D: '#F97316',
  E: '#A78BFA', F: '#EC4899', G: '#14B8A6', H: '#FB923C',
  I: '#60A5FA', J: '#34D399', K: '#F472B6', L: '#FBBF24',
}
